Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -140,23 +140,169 @@ jobs:
             exit 1
           fi
         
+name: iOS starter workflow               
+on:             
+  push:       
+    branches:              
+      - main                         
+  pull_request:         
+    branches:          
+      - main     
+env:
+  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
+  PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}
+
+jobs:
+  build: 
+    name: Build and Test default scheme using any available iPhone simulator
+    runs-on: macos-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: check Xcode version
+        run: /usr/bin/xcodebuild -version
+        
+      - name: Clear Derived Data
+        run: |
+          rm -rf ~/Library/Developer/Xcode/DerivedData
+              
+      - name: Install the Apple certificate and provisioning profile
+        env:
+          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
+        run: |
+          # Copy the certificate and provisioning profile to the correct locations
+          cp Certificates.p12 $RUNNER_TEMP/build_certificate.p12
+          cp DemoTest.mobileprovision $RUNNER_TEMP/build_pp.mobileprovision
+
+          # Import the certificate to the user keychain
+          security import $RUNNER_TEMP/build_certificate.p12 -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k ~/Library/Keychains/login.keychain-db
+          security list-keychain -d user -s ~/Library/Keychains/login.keychain-db
+
+          # Apply the provisioning profile
+          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
+          cp $RUNNER_TEMP/build_pp.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles
+
+   #   - name: Read Provisioning Profile Specifier from "DemoTest.mobileprovision"
+  #      run: |
+  #        PROVISIONING_PROFILE_SPECIFIER=$(security cms -D -i "$DEMOTEST_MOBILEPROVISION_FILE" | grep -A1 "Name" | grep -o -e '<string>.*</string>' | grep -o -e '>.*<' | sed 's/[><]//g')
+   #       echo "PROVISIONING_PROFILE_SPECIFIER: $PROVISIONING_PROFILE_SPECIFIER"
+   #       shell: /bin/bash
+ 
+
+      - name: check Xcode version
+        run: /usr/bin/xcodebuild -version
+
+      - name: Copy Podfile
+        run: cp -r SignIn/Podfile .
+
+      - name: Install CocoaPods
+        run: |
+          sudo gem install cocoapods -v '1.11.2'
+          pod repo list
+          pod setup
+
+      - name: Install dependencies
+        run: pod install --project-directory=SignIn/
+
+      - name: Check current directory
+        run: |
+          pwd
+          ls -al
+
+      - name: Navigate to SignIn folder
+        run: |
+          cd SignIn/
+          ls
+
+      - name: Clean Build
+        run: xcodebuild clean -workspace SignIn/SignIn.xcworkspace -scheme SignIn
+
+      - name: Update provisioning profile specifier in Xcode project
+        run: |
+          gem install xcodeproj
+          ruby - <<EOF
+          require 'xcodeproj'
+
+          # Define the path to your Xcode project
+          project_path = 'SignIn/SignIn.xcodeproj'
+
+          # Define the target name
+          target_name = 'SignIn'
+
+          # Define the provisioning profile specifier
+          provisioning_profile_specifier = "DemoTest"
+
+          # Open the Xcode project
+          project = Xcodeproj::Project.open(project_path)
+
+          # Find the target
+          target = project.targets.find { |t| t.name == target_name }
+
+          # Update the provisioning profile settings
+          target.build_configuration_list.build_configurations.each do |configuration|
+            configuration.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = provisioning_profile_specifier
+          end
+
+          # Save the changes to the Xcode project file
+          project.save
+          EOF
+          
+      - name: Build and Archive
+        id: build_archive
+        run: |
+          xcodebuild archive -workspace SignIn/SignIn.xcworkspace \
+          -scheme SignIn -archivePath "$RUNNER_TEMP/SignIn.xcarchive" \
+          -sdk iphonesimulator -configuration Debug \
+          -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=16.2' \
+          clean archive DEVELOPMENT_TEAM="X372X3URRM" \
+          PROVISIONING_PROFILE_SPECIFIER="DemoTest" -allowProvisioningUpdates \
+          | tee build_output.txt
+          
+      - name: List files in $RUNNER_TEMP
+        run: |
+          ls -a "$RUNNER_TEMP"
+          ls -a "$RUNNER_TEMP/SignIn.xcarchive"
+          ls -a "$RUNNER_TEMP/SignIn.xcarchive/Products/Applications/"
+
+      - name: List files in $RUNNER_TEMP
+        run: |
+          ls -a "$RUNNER_TEMP"
+          echo "Current directory: $(pwd)"
+          echo "Is 'ExportOptions.plist' file present?"
+          if [ ! -f "ExportOptions.plist" ]; then
+            echo "Error: ExportOptions.plist not found in the root directory!"
+            exit 1
+          fi
+
+          echo "Is PROVISIONING_PROFILE_SPECIFIER set?"
+          if [ -z "$PROVISIONING_PROFILE_SPECIFIER" ]; then
+            echo "Error: PROVISIONING_PROFILE_SPECIFIER not set. Please set it to a valid provisioning profile name or identifier."
+            exit 1
+          fi
+        
       - name: Export IPA
         id: export_ipa
         run: |
-            xcodebuild -archivePath "$RUNNER_TEMP/SignIn.xcarchive" \
-             -exportOptionsPlist ExportOptions.plist \
-             -exportPath "$RUNNER_TEMP/build" \
-             -allowProvisioningUpdates \
-             -exportArchive \
-             -verbose | tee export_output.log
+          cd $RUNNER_TEMP
+          ls -a # List files in the current directory (for debugging)
+          echo "Current directory: $(pwd)"
+          xcodebuild -archivePath "$RUNNER_TEMP/SignIn.xcarchive" \
+            -exportOptionsPlist ExportOptions.plist \
+            -exportPath "$RUNNER_TEMP/build" \
+            -allowProvisioningUpdates \
+            -exportArchive \
+            -verbose | tee export_output.log
 
       - name: Capture build output
         if: ${{ success() }}
         run: |
-          echo "::set-output name=build_output::$(cat build_output.txt)"
+          build_output=$(cat export_output.log)
+          echo "::set-output name=build_output::$build_output"
 
       - name: Display build output (Optional)
         if: ${{ success() }}
         run: |
           echo "Build Output:"
-          cat $GITHUB_ENV
+          echo "${{ steps.<previous_step_id>.outputs.build_output }}"
