Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -94,22 +94,29 @@ jobs:
           project.save
           EOF
 
-      - name: Build and Archive
-        id: build_archive
-        run: |
-          xcodebuild archive -workspace SignIn/SignIn.xcworkspace \
-          -scheme SignIn -archivePath "$RUNNER_TEMP/SignIn.xcarchive" \
-          -sdk iphonesimulator -configuration Debug \
-          -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=16.2' \
-          clean archive DEVELOPMENT_TEAM="X372X3URRM" \
-          PROVISIONING_PROFILE_SPECIFIER="DemoTest" -allowProvisioningUpdates \
-          | tee build_output.txt
-
       - name: List files in $RUNNER_TEMP
         run: |
           ls -a "$RUNNER_TEMP"
           ls -a "$RUNNER_TEMP/SignIn.xcarchive"
           ls -a "$RUNNER_TEMP/SignIn.xcarchive/Products/Applications/"
+
+      - name: Verify ExportOptions.plist
+        run: |
+          if [ ! -f "ExportOptions.plist" ]; then
+            echo "Error: ExportOptions.plist not found in the root directory!"
+            exit 1
+          fi
+
+      - name: Verify Provisioning Profile Specifier and Development Team
+        run: |
+          if [ -z "$PROVISIONING_PROFILE_SPECIFIER" ]; then
+            echo "Error: PROVISIONING_PROFILE_SPECIFIER not set. Please set it to a valid provisioning profile name or identifier."
+            exit 1
+          fi
+          if [ -z "$DEVELOPMENT_TEAM" ]; then
+            echo "Error: DEVELOPMENT_TEAM not set. Please set it to your team's identifier or leave it empty if you are not using a team."
+            exit 1
+          fi
 
       - name: Export IPA
         id: export_ipa
@@ -125,7 +132,7 @@ jobs:
         if: ${{ success() }}
         run: |
           echo "::set-output name=build_output::$(cat build_output.txt)"
-      
+
       - name: Display build output (Optional)
         if: ${{ success() }}
         run: |
